import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en" className="w-full">
      <body className="w-full min-h-screen bg-gray-50">
        {children}
        {modal}
      </body>
    </html>
  );
}
